# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

reviews:
  path_filters:
    - '!node_modules/**'
    - '!pnpm-lock.yaml'
  path_instructions:
    - path: '**/*'
      instructions: |
        Do not make comments about jsdoc style comments
        Do not comment about using a structured logger
        All 5 architectures are supported for all databases unless noted otherwise:
        - darwin-arm64
        - darwin-x64
        - linux-arm64
        - linux-x64
        - win32-x64
        hostdb should serve as the source of truth for supported versions
        - https://raw.githubusercontent.com/robertjbass/hostdb/main/releases.json
        - https://raw.githubusercontent.com/robertjbass/hostdb/main/databases.json
        - https://raw.githubusercontent.com/robertjbass/hostdb/main/downloads.json
