/**
 * MongoDB Engine Implementation
 *
 * MongoDB is a document database that uses BSON format.
 * Like MySQL, this implementation uses system-installed MongoDB binaries.
 *
 * Required binaries:
 * - mongod: MongoDB server daemon
 * - mongosh: MongoDB shell
 * - mongodump: Backup utility
 * - mongorestore: Restore utility
 */

import { exec, spawn, ChildProcess } from 'child_process'
import { promisify } from 'util'
import { mkdir, rm, writeFile, readFile, stat, readdir, cp } from 'fs/promises'
import { existsSync } from 'fs'
import { join, dirname } from 'path'
import { BaseEngine, type InitOptions, type RunScriptOptions } from '../base-engine'
import { paths } from '../../config/paths'
import { getEngineDefaults } from '../../config/engine-defaults'
import { getBinaryPath, detectAllBinaries } from './binary-detection'
import { validateVersion, getSupportedVersions } from './version-validator'
import {
  createBackup,
  dumpFromConnectionString as dumpFromConnStr,
} from './backup'
import {
  restore as restoreBackup,
  detectBackupFormat as detectFormat,
} from './restore'
import type {
  ContainerConfig,
  ProgressCallback,
  ProcessResult,
  BackupFormat,
  RestoreResult,
  BackupOptions,
  BackupResult,
  DumpResult,
} from '../../types'

const execAsync = promisify(exec)

/**
 * MongoDB Engine class
 */
export class MongoDBEngine extends BaseEngine {
  name = 'mongodb'
  displayName = 'MongoDB'

  get supportedVersions(): string[] {
    return getSupportedVersions()
  }

  /**
   * Check if MongoDB binaries are installed (uses system binaries)
   */
  async isBinaryInstalled(_version: string): Promise<boolean> {
    const mongodPath = await getBinaryPath('mongod')
    return !!mongodPath
  }

  /**
   * Ensure MongoDB binaries are available
   * For MongoDB, this just verifies system binaries exist
   */
  async ensureBinaries(
    _version: string,
    _onProgress?: ProgressCallback,
  ): Promise<void> {
    const mongodPath = await getBinaryPath('mongod')
    if (!mongodPath) {
      throw new Error(
        'MongoDB server (mongod) not found. Install MongoDB:\n' +
          '  macOS: brew tap mongodb/brew && brew install mongodb-community\n' +
          '  Linux: See https://www.mongodb.com/docs/manual/installation/',
      )
    }
  }

  /**
   * Initialize the MongoDB data directory
   */
  async initDataDir(
    containerName: string,
    version: string,
    options: InitOptions = {},
  ): Promise<void> {
    validateVersion(version)

    const containerPath = paths.getContainerPath(containerName, {
      engine: this.name,
    })
    const dataPath = paths.getContainerDataPath(containerName, {
      engine: this.name,
    })

    // Create data directory
    await mkdir(dataPath, { recursive: true })

    // Get defaults
    const defaults = getEngineDefaults(this.name)
    const maxConnections = options.maxConnections ?? defaults.maxConnections

    // Create MongoDB config file
    const configPath = join(containerPath, 'mongod.conf')
    const logPath = paths.getContainerLogPath(containerName, {
      engine: this.name,
    })
    const pidPath = paths.getContainerPidPath(containerName, {
      engine: this.name,
    })

    // MongoDB YAML configuration
    const config = `# MongoDB configuration for ${containerName}
# Generated by SpinDB

storage:
  dbPath: ${dataPath}
  journal:
    enabled: true

systemLog:
  destination: file
  path: ${logPath}
  logAppend: true

net:
  port: 27017
  bindIp: 127.0.0.1
  maxIncomingConnections: ${maxConnections}

processManagement:
  pidFilePath: ${pidPath}
  fork: true

# Security disabled for local development
# To enable authentication, uncomment:
# security:
#   authorization: enabled
`

    await writeFile(configPath, config, 'utf-8')
  }

  /**
   * Start a MongoDB container
   */
  async start(container: ContainerConfig): Promise<void> {
    const mongodPath = await getBinaryPath('mongod')
    if (!mongodPath) {
      throw new Error('mongod not found. Please install MongoDB.')
    }

    const containerPath = paths.getContainerPath(container.name, {
      engine: this.name,
    })
    const dataPath = paths.getContainerDataPath(container.name, {
      engine: this.name,
    })
    const logPath = paths.getContainerLogPath(container.name, {
      engine: this.name,
    })
    const pidPath = paths.getContainerPidPath(container.name, {
      engine: this.name,
    })
    const configPath = join(containerPath, 'mongod.conf')

    // Ensure directories exist
    if (!existsSync(dataPath)) {
      await mkdir(dataPath, { recursive: true })
    }

    // Build mongod command
    // We'll use command-line args instead of config file for more control
    const args: string[] = [
      '--dbpath',
      dataPath,
      '--port',
      String(container.port),
      '--bind_ip',
      '127.0.0.1',
      '--logpath',
      logPath,
      '--logappend',
      '--pidfilepath',
      pidPath,
      '--fork', // Run as daemon
    ]

    try {
      // Start MongoDB
      await execAsync(`"${mongodPath}" ${args.join(' ')}`)

      // Wait for MongoDB to be ready
      await this.waitForReady(container, 30000)
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to start MongoDB: ${e.message}`)
    }
  }

  /**
   * Stop a MongoDB container
   */
  async stop(container: ContainerConfig): Promise<void> {
    const mongoshPath = await getBinaryPath('mongosh')

    // Try graceful shutdown using mongosh admin command
    if (mongoshPath) {
      try {
        await execAsync(
          `"${mongoshPath}" --port ${container.port} --eval "db.adminCommand({ shutdown: 1 })" admin`,
          { timeout: 10000 },
        )
        // Wait for process to actually stop
        await this.waitForStop(container, 10000)
        return
      } catch {
        // Shutdown command failed, try alternate methods
      }
    }

    // Try using the PID file
    const pidPath = paths.getContainerPidPath(container.name, {
      engine: this.name,
    })

    if (existsSync(pidPath)) {
      try {
        const pid = (await readFile(pidPath, 'utf-8')).trim()
        if (pid) {
          // Send SIGTERM for graceful shutdown
          await execAsync(`kill ${pid}`).catch(() => {})
          await this.waitForStop(container, 10000)
          return
        }
      } catch {
        // PID file read failed
      }
    }

    // Last resort: kill by port
    try {
      const { stdout } = await execAsync(
        `lsof -ti :${container.port} | head -1`,
      )
      const pid = stdout.trim()
      if (pid) {
        await execAsync(`kill ${pid}`)
        await this.waitForStop(container, 10000)
      }
    } catch {
      // No process found on port
    }
  }

  /**
   * Check if a container is running
   */
  async isRunning(container: ContainerConfig): Promise<boolean> {
    try {
      const mongoshPath = await getBinaryPath('mongosh')
      if (mongoshPath) {
        await execAsync(
          `"${mongoshPath}" --port ${container.port} --eval "db.runCommand({ ping: 1 })" --quiet`,
          { timeout: 5000 },
        )
        return true
      }

      // Fallback: check if something is listening on the port
      const { stdout } = await execAsync(`lsof -i :${container.port} | grep LISTEN`)
      return stdout.includes('mongod')
    } catch {
      return false
    }
  }

  /**
   * Wait for MongoDB to be ready
   */
  private async waitForReady(
    container: ContainerConfig,
    timeoutMs: number,
  ): Promise<void> {
    const startTime = Date.now()
    const mongoshPath = await getBinaryPath('mongosh')

    while (Date.now() - startTime < timeoutMs) {
      try {
        if (mongoshPath) {
          await execAsync(
            `"${mongoshPath}" --port ${container.port} --eval "db.runCommand({ ping: 1 })" --quiet`,
            { timeout: 3000 },
          )
          return
        }
      } catch {
        // Not ready yet
      }
      await new Promise((resolve) => setTimeout(resolve, 500))
    }

    throw new Error(`MongoDB did not become ready within ${timeoutMs}ms`)
  }

  /**
   * Wait for MongoDB to stop
   */
  private async waitForStop(
    container: ContainerConfig,
    timeoutMs: number,
  ): Promise<void> {
    const startTime = Date.now()

    while (Date.now() - startTime < timeoutMs) {
      const running = await this.isRunning(container)
      if (!running) {
        return
      }
      await new Promise((resolve) => setTimeout(resolve, 500))
    }
  }

  /**
   * Create a database in MongoDB
   * Note: MongoDB creates databases implicitly when first written to
   */
  async createDatabase(
    container: ContainerConfig,
    database: string,
  ): Promise<void> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    // MongoDB creates databases lazily, so we just switch to it and create a placeholder collection
    // This ensures the database appears in listDatabases
    try {
      await execAsync(
        `"${mongoshPath}" --port ${container.port} ${database} --eval "db.createCollection('_spindb_init')"`,
        { timeout: 10000 },
      )
      // Clean up the placeholder collection
      await execAsync(
        `"${mongoshPath}" --port ${container.port} ${database} --eval "db._spindb_init.drop()"`,
        { timeout: 10000 },
      )
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to create database "${database}": ${e.message}`)
    }
  }

  /**
   * Drop a database
   */
  async dropDatabase(
    container: ContainerConfig,
    database: string,
  ): Promise<void> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    try {
      await execAsync(
        `"${mongoshPath}" --port ${container.port} ${database} --eval "db.dropDatabase()"`,
        { timeout: 10000 },
      )
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to drop database "${database}": ${e.message}`)
    }
  }

  /**
   * List all databases
   */
  async listDatabases(container: ContainerConfig): Promise<string[]> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    try {
      const { stdout } = await execAsync(
        `"${mongoshPath}" --port ${container.port} --eval "db.adminCommand('listDatabases').databases.map(d => d.name).join('\\n')" --quiet`,
        { timeout: 10000 },
      )

      return stdout
        .trim()
        .split('\n')
        .filter((db) => db && !['admin', 'config', 'local'].includes(db))
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to list databases: ${e.message}`)
    }
  }

  /**
   * Get connection string for a container
   */
  getConnectionString(container: ContainerConfig, database?: string): string {
    const db = database || container.database || 'test'
    return `mongodb://127.0.0.1:${container.port}/${db}`
  }

  /**
   * Get the size of all databases in bytes
   */
  async getDatabaseSize(container: ContainerConfig): Promise<number> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      return 0
    }

    try {
      const { stdout } = await execAsync(
        `"${mongoshPath}" --port ${container.port} --eval "db.adminCommand('listDatabases').totalSize" --quiet`,
        { timeout: 10000 },
      )

      const size = parseInt(stdout.trim(), 10)
      return isNaN(size) ? 0 : size
    } catch {
      return 0
    }
  }

  /**
   * Run a JavaScript file or inline script against MongoDB
   */
  async runScript(
    container: ContainerConfig,
    options: RunScriptOptions,
  ): Promise<ProcessResult> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    const database = options.database || container.database || 'test'
    const uri = `mongodb://127.0.0.1:${container.port}/${database}`

    let command: string

    if (options.file) {
      // Run a file
      command = `"${mongoshPath}" "${uri}" "${options.file}"`
    } else if (options.sql) {
      // Run inline JavaScript (note: MongoDB uses JS, not SQL, but we keep the interface consistent)
      // Escape quotes in the script
      const script = options.sql.replace(/"/g, '\\"')
      command = `"${mongoshPath}" "${uri}" --eval "${script}"`
    } else {
      throw new Error('Either file or sql option must be provided')
    }

    try {
      const { stdout, stderr } = await execAsync(command, { timeout: 60000 })
      return { stdout, stderr, code: 0 }
    } catch (err) {
      const e = err as Error & { code?: number; stdout?: string; stderr?: string }
      return {
        stdout: e.stdout || '',
        stderr: e.stderr || e.message,
        code: e.code || 1,
      }
    }
  }

  /**
   * Create a backup
   */
  async backup(
    container: ContainerConfig,
    outputPath: string,
    options: BackupOptions,
  ): Promise<BackupResult> {
    return createBackup(container, outputPath, {
      database: options.database,
      format: options.format === 'dump' ? 'archive' : 'archive',
    })
  }

  /**
   * Restore from a backup
   */
  async restore(
    container: ContainerConfig,
    backupPath: string,
    options: { database?: string; createDatabase?: boolean },
  ): Promise<RestoreResult> {
    return restoreBackup(container, backupPath, options)
  }

  /**
   * Detect backup format
   */
  async detectBackupFormat(backupPath: string): Promise<BackupFormat> {
    return detectFormat(backupPath)
  }

  /**
   * Dump from a connection string (for remote → local restore)
   */
  async dumpFromConnectionString(
    connectionString: string,
    outputPath: string,
  ): Promise<DumpResult> {
    return dumpFromConnStr(connectionString, outputPath)
  }

  /**
   * Fetch available versions
   * For MongoDB, we just return the supported versions since we use system binaries
   */
  async fetchAvailableVersions(): Promise<Record<string, string[]>> {
    const supported = getSupportedVersions()
    const result: Record<string, string[]> = {}

    // For each major.minor version, we just return the base version
    // since MongoDB uses system-installed binaries and we can't easily
    // enumerate all available patch versions
    for (const version of supported) {
      result[version] = [version]
    }

    return result
  }

  /**
   * Clone a container's data to a new container
   */
  async clone(
    sourceContainer: ContainerConfig,
    targetContainerName: string,
  ): Promise<void> {
    const sourceDataPath = paths.getContainerDataPath(sourceContainer.name, {
      engine: this.name,
    })
    const targetDataPath = paths.getContainerDataPath(targetContainerName, {
      engine: this.name,
    })

    // Create target directory
    await mkdir(dirname(targetDataPath), { recursive: true })

    // Copy data directory
    await cp(sourceDataPath, targetDataPath, { recursive: true })
  }
}

// Export singleton instance
export const mongodbEngine = new MongoDBEngine()
