/**
 * MongoDB Engine Implementation
 *
 * MongoDB is a document database that uses BSON format.
 * Like MySQL, this implementation uses system-installed MongoDB binaries.
 *
 * Required binaries:
 * - mongod: MongoDB server daemon
 * - mongosh: MongoDB shell
 * - mongodump: Backup utility
 * - mongorestore: Restore utility
 */

import { spawn, exec } from 'child_process'
import { promisify } from 'util'
import { mkdir, writeFile, readFile, unlink, cp } from 'fs/promises'
import { existsSync } from 'fs'
import { join, dirname } from 'path'
import { BaseEngine } from '../base-engine'
import { paths } from '../../config/paths'
import { getEngineDefaults } from '../../config/defaults'
import { getBinaryPath } from './binary-detection'
import { validateVersion, getSupportedVersions } from './version-validator'
import {
  createBackup,
  dumpFromConnectionString as dumpFromConnStr,
} from './backup'
import {
  restore as restoreBackup,
  detectBackupFormat as detectFormat,
} from './restore'
import type {
  ContainerConfig,
  ProgressCallback,
  BackupFormat,
  BackupOptions,
  BackupResult,
  RestoreResult,
  DumpResult,
  StatusResult,
} from '../../types'

// Re-export modules for external access
export * from './version-validator'
export * from './restore'

const execAsync = promisify(exec)

const ENGINE = 'mongodb'
const engineDef = getEngineDefaults(ENGINE)

/**
 * Get installation instructions for MongoDB
 */
function getInstallInstructions(): string {
  return (
    'MongoDB not found. Install MongoDB:\n' +
    '  macOS: brew tap mongodb/brew && brew install mongodb-community\n' +
    '  Ubuntu/Debian: See https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/\n' +
    '  Other Linux: See https://www.mongodb.com/docs/manual/installation/'
  )
}

/**
 * MongoDB Engine class
 */
export class MongoDBEngine extends BaseEngine {
  name = ENGINE
  displayName = 'MongoDB'
  defaultPort = engineDef.defaultPort
  supportedVersions = engineDef.supportedVersions

  /**
   * Get binary download URL - not applicable for MongoDB (uses system binaries)
   */
  getBinaryUrl(_version: string, _platform: string, _arch: string): string {
    throw new Error(
      'MongoDB uses system-installed binaries. ' + getInstallInstructions(),
    )
  }

  /**
   * Verify that MongoDB binaries are available
   */
  async verifyBinary(_binPath: string): Promise<boolean> {
    const mongod = await getBinaryPath('mongod')
    return mongod !== null
  }

  /**
   * Check if MongoDB binaries are installed (uses system binaries)
   */
  async isBinaryInstalled(_version: string): Promise<boolean> {
    const mongodPath = await getBinaryPath('mongod')
    return !!mongodPath
  }

  /**
   * Ensure MongoDB binaries are available
   * For MongoDB, this just verifies system binaries exist
   */
  async ensureBinaries(
    _version: string,
    _onProgress?: ProgressCallback,
  ): Promise<string> {
    const mongodPath = await getBinaryPath('mongod')
    if (!mongodPath) {
      throw new Error(getInstallInstructions())
    }
    return mongodPath
  }

  /**
   * Fetch available versions from system
   * Unlike PostgreSQL which downloads binaries, MongoDB uses system-installed versions
   */
  async fetchAvailableVersions(): Promise<Record<string, string[]>> {
    const versions: Record<string, string[]> = {}

    // For MongoDB, we return the supported versions since we use system binaries
    for (const v of this.supportedVersions) {
      versions[v] = [v]
    }

    return versions
  }

  /**
   * Initialize the MongoDB data directory
   */
  async initDataDir(
    containerName: string,
    version: string,
    options: Record<string, unknown> = {},
  ): Promise<string> {
    validateVersion(version)

    const containerPath = paths.getContainerPath(containerName, {
      engine: this.name,
    })
    const dataPath = paths.getContainerDataPath(containerName, {
      engine: this.name,
    })

    // Create data directory
    await mkdir(dataPath, { recursive: true })

    // Get defaults
    const maxConnections =
      (options.maxConnections as number) ?? engineDef.maxConnections

    // Create MongoDB config file
    const configPath = join(containerPath, 'mongod.conf')
    const logPath = paths.getContainerLogPath(containerName, {
      engine: this.name,
    })
    const pidPath = paths.getContainerPidPath(containerName, {
      engine: this.name,
    })

    // MongoDB YAML configuration
    const config = `# MongoDB configuration for ${containerName}
# Generated by SpinDB

storage:
  dbPath: ${dataPath}
  journal:
    enabled: true

systemLog:
  destination: file
  path: ${logPath}
  logAppend: true

net:
  port: 27017
  bindIp: 127.0.0.1
  maxIncomingConnections: ${maxConnections}

processManagement:
  pidFilePath: ${pidPath}
  fork: true

# Security disabled for local development
# To enable authentication, uncomment:
# security:
#   authorization: enabled
`

    await writeFile(configPath, config, 'utf-8')

    return dataPath
  }

  /**
   * Start a MongoDB container
   */
  async start(
    container: ContainerConfig,
    onProgress?: ProgressCallback,
  ): Promise<{ port: number; connectionString: string }> {
    const { name, port } = container

    const mongodPath = await getBinaryPath('mongod')
    if (!mongodPath) {
      throw new Error(getInstallInstructions())
    }

    const dataPath = paths.getContainerDataPath(name, { engine: ENGINE })
    const logPath = paths.getContainerLogPath(name, { engine: ENGINE })
    const pidPath = paths.getContainerPidPath(name, { engine: ENGINE })

    // Ensure directories exist
    if (!existsSync(dataPath)) {
      await mkdir(dataPath, { recursive: true })
    }

    onProgress?.({ stage: 'starting', message: 'Starting MongoDB...' })

    // Build mongod command arguments
    const args: string[] = [
      '--dbpath',
      dataPath,
      '--port',
      String(port),
      '--bind_ip',
      '127.0.0.1',
      '--logpath',
      logPath,
      '--logappend',
      '--pidfilepath',
      pidPath,
      '--fork', // Run as daemon
    ]

    try {
      // Start MongoDB
      await execAsync(`"${mongodPath}" ${args.join(' ')}`)

      // Wait for MongoDB to be ready
      await this.waitForReady(container, 30000)

      return {
        port,
        connectionString: this.getConnectionString(container),
      }
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to start MongoDB: ${e.message}`)
    }
  }

  /**
   * Stop a MongoDB container
   */
  async stop(container: ContainerConfig): Promise<void> {
    const { name, port } = container
    const pidFile = paths.getContainerPidPath(name, { engine: ENGINE })

    // Try graceful shutdown using mongosh admin command
    const mongoshPath = await getBinaryPath('mongosh')
    if (mongoshPath) {
      try {
        await execAsync(
          `"${mongoshPath}" --port ${port} --eval "db.adminCommand({ shutdown: 1 })" admin`,
          { timeout: 10000 },
        )
        // Wait for process to actually stop
        await this.waitForStop(container, 10000)
        await this.cleanupPidFile(pidFile)
        return
      } catch {
        // Shutdown command failed, try alternate methods
      }
    }

    // Try using the PID file
    const pid = await this.getValidatedPid(pidFile)
    if (pid !== null) {
      // Try SIGTERM first for graceful shutdown
      try {
        process.kill(pid, 'SIGTERM')
        await this.waitForStop(container, 10000)
        await this.cleanupPidFile(pidFile)
        return
      } catch {
        // SIGTERM failed, try SIGKILL
        try {
          process.kill(pid, 'SIGKILL')
          await this.sleep(1000)
          await this.cleanupPidFile(pidFile)
          return
        } catch {
          // Process may already be dead
        }
      }
    }

    // Last resort: kill by port
    try {
      const { stdout } = await execAsync(`lsof -ti :${port} | head -1`)
      const portPid = stdout.trim()
      if (portPid) {
        await execAsync(`kill ${portPid}`)
        await this.waitForStop(container, 5000)
      }
    } catch {
      // No process found on port
    }

    await this.cleanupPidFile(pidFile)
  }

  /**
   * Get MongoDB server status
   */
  async status(container: ContainerConfig): Promise<StatusResult> {
    const { name, port } = container
    const pidFile = paths.getContainerPidPath(name, { engine: ENGINE })

    // Check if PID file exists
    if (!existsSync(pidFile)) {
      return { running: false, message: 'MongoDB is not running' }
    }

    // Try to ping MongoDB
    const mongoshPath = await getBinaryPath('mongosh')
    if (mongoshPath) {
      try {
        await execAsync(
          `"${mongoshPath}" --port ${port} --eval "db.runCommand({ ping: 1 })" --quiet`,
          { timeout: 5000 },
        )
        return { running: true, message: 'MongoDB is running' }
      } catch {
        return { running: false, message: 'MongoDB is not responding' }
      }
    }

    // Fall back to checking PID
    const pid = await this.getValidatedPid(pidFile)
    if (pid !== null) {
      return { running: true, message: `MongoDB is running (PID: ${pid})` }
    }

    return { running: false, message: 'MongoDB is not running' }
  }

  /**
   * Open mongosh interactive shell
   */
  async connect(container: ContainerConfig, database?: string): Promise<void> {
    const { port } = container
    const db = database || container.database || 'test'

    const mongosh = await getBinaryPath('mongosh')
    if (!mongosh) {
      throw new Error(
        'mongosh not found. Install MongoDB shell:\n' +
          '  macOS: brew install mongosh\n' +
          '  Ubuntu/Debian: See https://www.mongodb.com/docs/mongodb-shell/install/',
      )
    }

    const uri = `mongodb://127.0.0.1:${port}/${db}`

    return new Promise((resolve, reject) => {
      const proc = spawn(mongosh, [uri], { stdio: 'inherit' })

      proc.on('error', reject)
      proc.on('close', () => resolve())
    })
  }

  /**
   * Get and validate PID from PID file
   * Returns null if PID file doesn't exist, is corrupt, or references dead process
   */
  private async getValidatedPid(pidFile: string): Promise<number | null> {
    if (!existsSync(pidFile)) {
      return null
    }

    try {
      const content = await readFile(pidFile, 'utf8')
      const pid = parseInt(content.trim(), 10)

      if (isNaN(pid) || pid <= 0) {
        // Clean up corrupt PID file
        await this.cleanupPidFile(pidFile)
        return null
      }

      // Verify process exists
      try {
        process.kill(pid, 0) // Signal 0 = check existence
        return pid
      } catch {
        // Process is gone, clean up stale PID file
        await this.cleanupPidFile(pidFile)
        return null
      }
    } catch {
      return null
    }
  }

  /**
   * Clean up PID file
   */
  private async cleanupPidFile(pidFile: string): Promise<void> {
    try {
      await unlink(pidFile)
    } catch (err) {
      const e = err as NodeJS.ErrnoException
      if (e.code !== 'ENOENT') {
        // Ignore "file not found" errors
      }
    }
  }

  /**
   * Sleep helper
   */
  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms))
  }

  /**
   * Check if a container is running
   */
  async isRunning(container: ContainerConfig): Promise<boolean> {
    try {
      const mongoshPath = await getBinaryPath('mongosh')
      if (mongoshPath) {
        await execAsync(
          `"${mongoshPath}" --port ${container.port} --eval "db.runCommand({ ping: 1 })" --quiet`,
          { timeout: 5000 },
        )
        return true
      }

      // Fallback: check if something is listening on the port
      const { stdout } = await execAsync(
        `lsof -i :${container.port} | grep LISTEN`,
      )
      return stdout.includes('mongod')
    } catch {
      return false
    }
  }

  /**
   * Wait for MongoDB to be ready
   */
  private async waitForReady(
    container: ContainerConfig,
    timeoutMs: number,
  ): Promise<void> {
    const startTime = Date.now()
    const mongoshPath = await getBinaryPath('mongosh')

    while (Date.now() - startTime < timeoutMs) {
      try {
        if (mongoshPath) {
          await execAsync(
            `"${mongoshPath}" --port ${container.port} --eval "db.runCommand({ ping: 1 })" --quiet`,
            { timeout: 3000 },
          )
          return
        }
      } catch {
        // Not ready yet
      }
      await this.sleep(500)
    }

    throw new Error(`MongoDB did not become ready within ${timeoutMs}ms`)
  }

  /**
   * Wait for MongoDB to stop
   */
  private async waitForStop(
    container: ContainerConfig,
    timeoutMs: number,
  ): Promise<void> {
    const startTime = Date.now()

    while (Date.now() - startTime < timeoutMs) {
      const running = await this.isRunning(container)
      if (!running) {
        return
      }
      await this.sleep(500)
    }
  }

  /**
   * Create a database in MongoDB
   * Note: MongoDB creates databases implicitly when first written to
   */
  async createDatabase(
    container: ContainerConfig,
    database: string,
  ): Promise<void> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    // MongoDB creates databases lazily, so we just switch to it and create a placeholder collection
    // This ensures the database appears in listDatabases
    try {
      await execAsync(
        `"${mongoshPath}" --port ${container.port} ${database} --eval "db.createCollection('_spindb_init')"`,
        { timeout: 10000 },
      )
      // Clean up the placeholder collection
      await execAsync(
        `"${mongoshPath}" --port ${container.port} ${database} --eval "db._spindb_init.drop()"`,
        { timeout: 10000 },
      )
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to create database "${database}": ${e.message}`)
    }
  }

  /**
   * Drop a database
   */
  async dropDatabase(
    container: ContainerConfig,
    database: string,
  ): Promise<void> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    try {
      await execAsync(
        `"${mongoshPath}" --port ${container.port} ${database} --eval "db.dropDatabase()"`,
        { timeout: 10000 },
      )
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to drop database "${database}": ${e.message}`)
    }
  }

  /**
   * List all databases
   */
  async listDatabases(container: ContainerConfig): Promise<string[]> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    try {
      const { stdout } = await execAsync(
        `"${mongoshPath}" --port ${container.port} --eval "db.adminCommand('listDatabases').databases.map(d => d.name).join('\\n')" --quiet`,
        { timeout: 10000 },
      )

      return stdout
        .trim()
        .split('\n')
        .filter((db) => db && !['admin', 'config', 'local'].includes(db))
    } catch (err) {
      const e = err as Error
      throw new Error(`Failed to list databases: ${e.message}`)
    }
  }

  /**
   * Get connection string for a container
   */
  getConnectionString(container: ContainerConfig, database?: string): string {
    const db = database || container.database || 'test'
    return `mongodb://127.0.0.1:${container.port}/${db}`
  }

  /**
   * Get the size of all databases in bytes
   * Returns null if container is not running or query fails
   */
  async getDatabaseSize(container: ContainerConfig): Promise<number | null> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      return null
    }

    try {
      const { stdout } = await execAsync(
        `"${mongoshPath}" --port ${container.port} --eval "db.adminCommand('listDatabases').totalSize" --quiet`,
        { timeout: 10000 },
      )

      const size = parseInt(stdout.trim(), 10)
      return isNaN(size) ? null : size
    } catch {
      return null
    }
  }

  /**
   * Run a JavaScript file or inline script against MongoDB
   */
  async runScript(
    container: ContainerConfig,
    options: { file?: string; sql?: string; database?: string },
  ): Promise<void> {
    const mongoshPath = await getBinaryPath('mongosh')
    if (!mongoshPath) {
      throw new Error('mongosh not found. Please install MongoDB shell.')
    }

    const { port } = container
    const database = options.database || container.database || 'test'
    const uri = `mongodb://127.0.0.1:${port}/${database}`

    if (options.sql) {
      // Run inline JavaScript (note: MongoDB uses JS, not SQL, but we keep the interface consistent)
      const args = [uri, '--eval', options.sql]

      return new Promise((resolve, reject) => {
        const proc = spawn(mongoshPath, args, { stdio: 'inherit' })

        proc.on('error', reject)
        proc.on('close', (code) => {
          if (code === 0) {
            resolve()
          } else {
            reject(new Error(`mongosh exited with code ${code}`))
          }
        })
      })
    } else if (options.file) {
      // Run a JavaScript file
      const args = [uri, options.file]

      return new Promise((resolve, reject) => {
        const proc = spawn(mongoshPath, args, { stdio: 'inherit' })

        proc.on('error', reject)
        proc.on('close', (code) => {
          if (code === 0) {
            resolve()
          } else {
            reject(new Error(`mongosh exited with code ${code}`))
          }
        })
      })
    } else {
      throw new Error('Either file or sql option must be provided')
    }
  }

  /**
   * Detect backup format
   */
  async detectBackupFormat(filePath: string): Promise<BackupFormat> {
    return detectFormat(filePath)
  }

  /**
   * Create a backup
   */
  async backup(
    container: ContainerConfig,
    outputPath: string,
    options: BackupOptions,
  ): Promise<BackupResult> {
    return createBackup(container, outputPath, {
      database: options.database,
      format: options.format === 'dump' ? 'archive' : 'archive',
    })
  }

  /**
   * Restore from a backup
   */
  async restore(
    container: ContainerConfig,
    backupPath: string,
    options: Record<string, unknown> = {},
  ): Promise<RestoreResult> {
    const database = (options.database as string) || container.database
    const createDatabase = options.createDatabase !== false
    const drop = options.drop !== false

    return restoreBackup(container, backupPath, {
      database,
      createDatabase,
      drop,
    })
  }

  /**
   * Dump from a connection string (for remote → local restore)
   */
  async dumpFromConnectionString(
    connectionString: string,
    outputPath: string,
  ): Promise<DumpResult> {
    return dumpFromConnStr(connectionString, outputPath)
  }

  /**
   * Clone a container's data to a new container
   */
  async clone(
    sourceContainer: ContainerConfig,
    targetContainerName: string,
  ): Promise<void> {
    const sourceDataPath = paths.getContainerDataPath(sourceContainer.name, {
      engine: this.name,
    })
    const targetDataPath = paths.getContainerDataPath(targetContainerName, {
      engine: this.name,
    })

    // Create target directory
    await mkdir(dirname(targetDataPath), { recursive: true })

    // Copy data directory
    await cp(sourceDataPath, targetDataPath, { recursive: true })
  }
}

// Export singleton instance
export const mongodbEngine = new MongoDBEngine()
